### ISSUE TITLE
Not relevant

### ISSUE THREAD

**Issue by bernikovich** [KrauseFx/watch.user#4]
Imho, this issue is not relevant at all.
How many app have access to your camera? ~0 big audience apps will use such data, because it can be detected easily and they will lose audience very quickly. At the same time I'm not sure how legal is it. Maybe it's real if unpopular app will photo you once, I don't think it's big issue.

**Comment by kanstantsin-bucha** [comment]
LOL) Any apple developer who works with a camera know this "feature". Any android app could do same thing, isn't it? The post is for "make some noise".
There are more relevant things like record an audio in background that author not mentioned.

**Comment by KrauseFx** [comment]
Thanks for your contribution :)
